# DO NOT EDIT THIS FILE!
#
# Python module _GlobalIDL generated by omniidl

import omniORB
omniORB.updateModule("_GlobalIDL")

# ** 1. Stub files contributing to this module
import pcProcessPort_idl
import imProcessPort_idl
import sv_GetInfo_idl

# ** 2. Sub-modules

# ** 3. End
