// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.

#include "pcProcessPort.hh"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

static const char* _0RL_library_version = omniORB_4_1;



ComPcProcess_ptr ComPcProcess_Helper::_nil() {
  return ::ComPcProcess::_nil();
}

::CORBA::Boolean ComPcProcess_Helper::is_nil(::ComPcProcess_ptr p) {
  return ::CORBA::is_nil(p);

}

void ComPcProcess_Helper::release(::ComPcProcess_ptr p) {
  ::CORBA::release(p);
}

void ComPcProcess_Helper::marshalObjRef(::ComPcProcess_ptr obj, cdrStream& s) {
  ::ComPcProcess::_marshalObjRef(obj, s);
}

ComPcProcess_ptr ComPcProcess_Helper::unmarshalObjRef(cdrStream& s) {
  return ::ComPcProcess::_unmarshalObjRef(s);
}

void ComPcProcess_Helper::duplicate(::ComPcProcess_ptr obj) {
  if( obj && !obj->_NP_is_nil() )  omni::duplicateObjRef(obj);
}

ComPcProcess_ptr
ComPcProcess::_duplicate(::ComPcProcess_ptr obj)
{
  if( obj && !obj->_NP_is_nil() )  omni::duplicateObjRef(obj);
  return obj;
}

ComPcProcess_ptr
ComPcProcess::_narrow(::CORBA::Object_ptr obj)
{
  if( !obj || obj->_NP_is_nil() || obj->_NP_is_pseudo() ) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


ComPcProcess_ptr
ComPcProcess::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if( !obj || obj->_NP_is_nil() || obj->_NP_is_pseudo() ) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

ComPcProcess_ptr
ComPcProcess::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_ComPcProcess _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_ComPcProcess* _the_nil_ptr = 0;
  if( !_the_nil_ptr ) {
    omni::nilRefLock().lock();
    if( !_the_nil_ptr ) {
      _the_nil_ptr = new _objref_ComPcProcess;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* ComPcProcess::_PD_repoId = "IDL:ComPcProcess:1.0";


_objref_ComPcProcess::~_objref_ComPcProcess() {
  
}


_objref_ComPcProcess::_objref_ComPcProcess(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::ComPcProcess::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
_objref_ComPcProcess::_ptrToObjRef(const char* id)
{
  if( id == ::ComPcProcess::_PD_repoId )
    return (::ComPcProcess_ptr) this;
  
  if( id == ::CORBA::Object::_PD_repoId )
    return (::CORBA::Object_ptr) this;

  if( omni::strMatch(id, ::ComPcProcess::_PD_repoId) )
    return (::ComPcProcess_ptr) this;
  
  if( omni::strMatch(id, ::CORBA::Object::_PD_repoId) )
    return (::CORBA::Object_ptr) this;

  return 0;
}

// Proxy call descriptor class. Mangled signature:
//  _a4_cRTC_mPointCloud_i_cshort_o_cboolean
class _0RL_cd_a93046d6d953ea9d_00000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_a93046d6d953ea9d_00000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::Short arg_0;
  ::CORBA::Boolean arg_1;
  ComPcProcess::MultiPointCloud_var result;
};

void _0RL_cd_a93046d6d953ea9d_00000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;

}

void _0RL_cd_a93046d6d953ea9d_00000000::unmarshalArguments(cdrStream& _n)
{
  (::CORBA::Short&)arg_0 <<= _n;

}

void _0RL_cd_a93046d6d953ea9d_00000000::marshalReturnedValues(cdrStream& _n)
{
  {
    for (_CORBA_ULong _0i0 = 0; _0i0 < 4; _0i0++){
      (const RTC::PointCloud&) result[_0i0] >>= _n;
    }
  }
  _n.marshalBoolean(arg_1);

}

void _0RL_cd_a93046d6d953ea9d_00000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = ComPcProcess::MultiPointCloud_alloc();
  {
    for (_CORBA_ULong _0i0 = 0; _0i0 < 4; _0i0++){
      (RTC::PointCloud&)result[_0i0] <<= _n;
    }
  }
  arg_1 = _n.unmarshalBoolean();

}

const char* const _0RL_cd_a93046d6d953ea9d_00000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_a93046d6d953ea9d_10000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_a93046d6d953ea9d_00000000* tcd = (_0RL_cd_a93046d6d953ea9d_00000000*)cd;
  _impl_ComPcProcess* impl = (_impl_ComPcProcess*) svnt->_ptrToInterface(ComPcProcess::_PD_repoId);
  tcd->result = impl->get_pointCloud(tcd->arg_0, tcd->arg_1);


}

ComPcProcess::MultiPointCloud_slice* _objref_ComPcProcess::get_pointCloud(::CORBA::Short CameraBitMask, ::CORBA::Boolean& flag)
{
  _0RL_cd_a93046d6d953ea9d_00000000 _call_desc(_0RL_lcfn_a93046d6d953ea9d_10000000, "get_pointCloud", 15);
  _call_desc.arg_0 = CameraBitMask;

  _invoke(_call_desc);
  flag = _call_desc.arg_1;
  return _call_desc.result._retn();


}
// Proxy call descriptor class. Mangled signature:
//  _cboolean_i_cshort_i_cstring
class _0RL_cd_a93046d6d953ea9d_20000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_a93046d6d953ea9d_20000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::Short arg_0;
  ::CORBA::String_var arg_1_;
  const char* arg_1;
  ::CORBA::Boolean result;
};

void _0RL_cd_a93046d6d953ea9d_20000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;
  _n.marshalString(arg_1,0);

}

void _0RL_cd_a93046d6d953ea9d_20000000::unmarshalArguments(cdrStream& _n)
{
  (::CORBA::Short&)arg_0 <<= _n;
  arg_1_ = _n.unmarshalString(0);
  arg_1 = arg_1_.in();

}

void _0RL_cd_a93046d6d953ea9d_20000000::marshalReturnedValues(cdrStream& _n)
{
  _n.marshalBoolean(result);

}

void _0RL_cd_a93046d6d953ea9d_20000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = _n.unmarshalBoolean();

}

const char* const _0RL_cd_a93046d6d953ea9d_20000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_a93046d6d953ea9d_30000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_a93046d6d953ea9d_20000000* tcd = (_0RL_cd_a93046d6d953ea9d_20000000*)cd;
  _impl_ComPcProcess* impl = (_impl_ComPcProcess*) svnt->_ptrToInterface(ComPcProcess::_PD_repoId);
  tcd->result = impl->save_pointCloud(tcd->arg_0, tcd->arg_1);


}

::CORBA::Boolean _objref_ComPcProcess::save_pointCloud(::CORBA::Short CameraBitMask, const char* str)
{
  _0RL_cd_a93046d6d953ea9d_20000000 _call_desc(_0RL_lcfn_a93046d6d953ea9d_30000000, "save_pointCloud", 16);
  _call_desc.arg_0 = CameraBitMask;
  _call_desc.arg_1 = str;

  _invoke(_call_desc);
  return _call_desc.result;


}
// Proxy call descriptor class. Mangled signature:
//  _clong_i_a4_a4_cfloat_o_a10_a10_cfloat_o_cdouble
class _0RL_cd_a93046d6d953ea9d_40000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_a93046d6d953ea9d_40000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ComPcProcess::Matrix4X4F arg_0_;
  const ComPcProcess::Matrix4X4F_slice* arg_0;
  ComPcProcess::plate_info arg_1_;
  ComPcProcess::plate_info_slice* arg_1;
  ::CORBA::Double arg_2;
  ::CORBA::Long result;
};

void _0RL_cd_a93046d6d953ea9d_40000000::marshalArguments(cdrStream& _n)
{
  if (! _n.marshal_byte_swap()) {
    _n.put_octet_array((_CORBA_Octet*)((ComPcProcess::Matrix4X4F_slice*)arg_0),64,omni::ALIGN_4);
  }
  else 
  {
    _n.declareArrayLength(omni::ALIGN_4, 64);
    for (_CORBA_ULong _0i0 = 0; _0i0 < 4; _0i0++){
      for (_CORBA_ULong _0i1 = 0; _0i1 < 4; _0i1++){
        arg_0[_0i0][_0i1] >>= _n;
      }
    }
  }

}

void _0RL_cd_a93046d6d953ea9d_40000000::unmarshalArguments(cdrStream& _n)
{
  _n.unmarshalArrayFloat((_CORBA_Float*)((ComPcProcess::Matrix4X4F_slice*)arg_0_), 16);
  arg_0 = &arg_0_[0];

}

void _0RL_cd_a93046d6d953ea9d_40000000::marshalReturnedValues(cdrStream& _n)
{
  result >>= _n;
  if (! _n.marshal_byte_swap()) {
    _n.put_octet_array((_CORBA_Octet*)((ComPcProcess::plate_info_slice*)arg_1),400,omni::ALIGN_4);
  }
  else 
  {
    _n.declareArrayLength(omni::ALIGN_4, 400);
    for (_CORBA_ULong _0i0 = 0; _0i0 < 10; _0i0++){
      for (_CORBA_ULong _0i1 = 0; _0i1 < 10; _0i1++){
        arg_1[_0i0][_0i1] >>= _n;
      }
    }
  }
  arg_2 >>= _n;

}

void _0RL_cd_a93046d6d953ea9d_40000000::unmarshalReturnedValues(cdrStream& _n)
{
  (::CORBA::Long&)result <<= _n;
  _n.unmarshalArrayFloat((_CORBA_Float*)((ComPcProcess::plate_info_slice*)arg_1), 100);
  (::CORBA::Double&)arg_2 <<= _n;

}

const char* const _0RL_cd_a93046d6d953ea9d_40000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_a93046d6d953ea9d_50000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_a93046d6d953ea9d_40000000* tcd = (_0RL_cd_a93046d6d953ea9d_40000000*)cd;
  _impl_ComPcProcess* impl = (_impl_ComPcProcess*) svnt->_ptrToInterface(ComPcProcess::_PD_repoId);
  tcd->result = impl->plate_recog(tcd->arg_0, tcd->arg_1, tcd->arg_2);


}

::CORBA::Long _objref_ComPcProcess::plate_recog(const ::ComPcProcess::Matrix4X4F matrix_in, ::ComPcProcess::plate_info information, ::CORBA::Double& r_max)
{
  _0RL_cd_a93046d6d953ea9d_40000000 _call_desc(_0RL_lcfn_a93046d6d953ea9d_50000000, "plate_recog", 12);
  _call_desc.arg_0 = &matrix_in[0];
  _call_desc.arg_1 = &information[0];

  _invoke(_call_desc);
  r_max = _call_desc.arg_2;
  return _call_desc.result;


}
// Proxy call descriptor class. Mangled signature:
//  _clong_i_a4_a4_cfloat
class _0RL_cd_a93046d6d953ea9d_60000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_a93046d6d953ea9d_60000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ComPcProcess::Matrix4X4F arg_0_;
  const ComPcProcess::Matrix4X4F_slice* arg_0;
  ::CORBA::Long result;
};

void _0RL_cd_a93046d6d953ea9d_60000000::marshalArguments(cdrStream& _n)
{
  if (! _n.marshal_byte_swap()) {
    _n.put_octet_array((_CORBA_Octet*)((ComPcProcess::Matrix4X4F_slice*)arg_0),64,omni::ALIGN_4);
  }
  else 
  {
    _n.declareArrayLength(omni::ALIGN_4, 64);
    for (_CORBA_ULong _0i0 = 0; _0i0 < 4; _0i0++){
      for (_CORBA_ULong _0i1 = 0; _0i1 < 4; _0i1++){
        arg_0[_0i0][_0i1] >>= _n;
      }
    }
  }

}

void _0RL_cd_a93046d6d953ea9d_60000000::unmarshalArguments(cdrStream& _n)
{
  _n.unmarshalArrayFloat((_CORBA_Float*)((ComPcProcess::Matrix4X4F_slice*)arg_0_), 16);
  arg_0 = &arg_0_[0];

}

void _0RL_cd_a93046d6d953ea9d_60000000::marshalReturnedValues(cdrStream& _n)
{
  result >>= _n;

}

void _0RL_cd_a93046d6d953ea9d_60000000::unmarshalReturnedValues(cdrStream& _n)
{
  (::CORBA::Long&)result <<= _n;

}

const char* const _0RL_cd_a93046d6d953ea9d_60000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_a93046d6d953ea9d_70000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_a93046d6d953ea9d_60000000* tcd = (_0RL_cd_a93046d6d953ea9d_60000000*)cd;
  _impl_ComPcProcess* impl = (_impl_ComPcProcess*) svnt->_ptrToInterface(ComPcProcess::_PD_repoId);
  tcd->result = impl->plate_modelling(tcd->arg_0);


}

::CORBA::Long _objref_ComPcProcess::plate_modelling(const ::ComPcProcess::Matrix4X4F matrix_in)
{
  _0RL_cd_a93046d6d953ea9d_60000000 _call_desc(_0RL_lcfn_a93046d6d953ea9d_70000000, "plate_modelling", 16);
  _call_desc.arg_0 = &matrix_in[0];

  _invoke(_call_desc);
  return _call_desc.result;


}
// Proxy call descriptor class. Mangled signature:
//  _cboolean_i_a4_a4_cfloat
class _0RL_cd_a93046d6d953ea9d_80000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_a93046d6d953ea9d_80000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ComPcProcess::Matrix4X4F arg_0_;
  const ComPcProcess::Matrix4X4F_slice* arg_0;
  ::CORBA::Boolean result;
};

void _0RL_cd_a93046d6d953ea9d_80000000::marshalArguments(cdrStream& _n)
{
  if (! _n.marshal_byte_swap()) {
    _n.put_octet_array((_CORBA_Octet*)((ComPcProcess::Matrix4X4F_slice*)arg_0),64,omni::ALIGN_4);
  }
  else 
  {
    _n.declareArrayLength(omni::ALIGN_4, 64);
    for (_CORBA_ULong _0i0 = 0; _0i0 < 4; _0i0++){
      for (_CORBA_ULong _0i1 = 0; _0i1 < 4; _0i1++){
        arg_0[_0i0][_0i1] >>= _n;
      }
    }
  }

}

void _0RL_cd_a93046d6d953ea9d_80000000::unmarshalArguments(cdrStream& _n)
{
  _n.unmarshalArrayFloat((_CORBA_Float*)((ComPcProcess::Matrix4X4F_slice*)arg_0_), 16);
  arg_0 = &arg_0_[0];

}

void _0RL_cd_a93046d6d953ea9d_80000000::marshalReturnedValues(cdrStream& _n)
{
  _n.marshalBoolean(result);

}

void _0RL_cd_a93046d6d953ea9d_80000000::unmarshalReturnedValues(cdrStream& _n)
{
  result = _n.unmarshalBoolean();

}

const char* const _0RL_cd_a93046d6d953ea9d_80000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_a93046d6d953ea9d_90000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_a93046d6d953ea9d_80000000* tcd = (_0RL_cd_a93046d6d953ea9d_80000000*)cd;
  _impl_ComPcProcess* impl = (_impl_ComPcProcess*) svnt->_ptrToInterface(ComPcProcess::_PD_repoId);
  tcd->result = impl->single_plate_modelling(tcd->arg_0);


}

::CORBA::Boolean _objref_ComPcProcess::single_plate_modelling(const ::ComPcProcess::Matrix4X4F matrix_in)
{
  _0RL_cd_a93046d6d953ea9d_80000000 _call_desc(_0RL_lcfn_a93046d6d953ea9d_90000000, "single_plate_modelling", 23);
  _call_desc.arg_0 = &matrix_in[0];

  _invoke(_call_desc);
  return _call_desc.result;


}
// Proxy call descriptor class. Mangled signature:
//  _cdouble_i_cdouble_i_cdouble_i_cdouble
class _0RL_cd_a93046d6d953ea9d_a0000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_a93046d6d953ea9d_a0000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::Double arg_0;
  ::CORBA::Double arg_1;
  ::CORBA::Double arg_2;
  ::CORBA::Double result;
};

void _0RL_cd_a93046d6d953ea9d_a0000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;
  arg_1 >>= _n;
  arg_2 >>= _n;

}

void _0RL_cd_a93046d6d953ea9d_a0000000::unmarshalArguments(cdrStream& _n)
{
  (::CORBA::Double&)arg_0 <<= _n;
  (::CORBA::Double&)arg_1 <<= _n;
  (::CORBA::Double&)arg_2 <<= _n;

}

void _0RL_cd_a93046d6d953ea9d_a0000000::marshalReturnedValues(cdrStream& _n)
{
  result >>= _n;

}

void _0RL_cd_a93046d6d953ea9d_a0000000::unmarshalReturnedValues(cdrStream& _n)
{
  (::CORBA::Double&)result <<= _n;

}

const char* const _0RL_cd_a93046d6d953ea9d_a0000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_a93046d6d953ea9d_b0000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_a93046d6d953ea9d_a0000000* tcd = (_0RL_cd_a93046d6d953ea9d_a0000000*)cd;
  _impl_ComPcProcess* impl = (_impl_ComPcProcess*) svnt->_ptrToInterface(ComPcProcess::_PD_repoId);
  tcd->result = impl->check_destination(tcd->arg_0, tcd->arg_1, tcd->arg_2);


}

::CORBA::Double _objref_ComPcProcess::check_destination(::CORBA::Double r, ::CORBA::Double x, ::CORBA::Double y)
{
  _0RL_cd_a93046d6d953ea9d_a0000000 _call_desc(_0RL_lcfn_a93046d6d953ea9d_b0000000, "check_destination", 18);
  _call_desc.arg_0 = r;
  _call_desc.arg_1 = x;
  _call_desc.arg_2 = y;

  _invoke(_call_desc);
  return _call_desc.result;


}
// Proxy call descriptor class. Mangled signature:
//  _cdouble_i_cdouble
class _0RL_cd_a93046d6d953ea9d_c0000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_a93046d6d953ea9d_c0000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::Double arg_0;
  ::CORBA::Double result;
};

void _0RL_cd_a93046d6d953ea9d_c0000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;

}

void _0RL_cd_a93046d6d953ea9d_c0000000::unmarshalArguments(cdrStream& _n)
{
  (::CORBA::Double&)arg_0 <<= _n;

}

void _0RL_cd_a93046d6d953ea9d_c0000000::marshalReturnedValues(cdrStream& _n)
{
  result >>= _n;

}

void _0RL_cd_a93046d6d953ea9d_c0000000::unmarshalReturnedValues(cdrStream& _n)
{
  (::CORBA::Double&)result <<= _n;

}

const char* const _0RL_cd_a93046d6d953ea9d_c0000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_a93046d6d953ea9d_d0000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_a93046d6d953ea9d_c0000000* tcd = (_0RL_cd_a93046d6d953ea9d_c0000000*)cd;
  _impl_ComPcProcess* impl = (_impl_ComPcProcess*) svnt->_ptrToInterface(ComPcProcess::_PD_repoId);
  tcd->result = impl->height_determine(tcd->arg_0);


}

::CORBA::Double _objref_ComPcProcess::height_determine(::CORBA::Double r)
{
  _0RL_cd_a93046d6d953ea9d_c0000000 _call_desc(_0RL_lcfn_a93046d6d953ea9d_d0000000, "height_determine", 17);
  _call_desc.arg_0 = r;

  _invoke(_call_desc);
  return _call_desc.result;


}
// Proxy call descriptor class. Mangled signature:
//  _cdouble_i_a4_a4_cfloat
class _0RL_cd_a93046d6d953ea9d_e0000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_a93046d6d953ea9d_e0000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ComPcProcess::Matrix4X4F arg_0_;
  const ComPcProcess::Matrix4X4F_slice* arg_0;
  ::CORBA::Double result;
};

void _0RL_cd_a93046d6d953ea9d_e0000000::marshalArguments(cdrStream& _n)
{
  if (! _n.marshal_byte_swap()) {
    _n.put_octet_array((_CORBA_Octet*)((ComPcProcess::Matrix4X4F_slice*)arg_0),64,omni::ALIGN_4);
  }
  else 
  {
    _n.declareArrayLength(omni::ALIGN_4, 64);
    for (_CORBA_ULong _0i0 = 0; _0i0 < 4; _0i0++){
      for (_CORBA_ULong _0i1 = 0; _0i1 < 4; _0i1++){
        arg_0[_0i0][_0i1] >>= _n;
      }
    }
  }

}

void _0RL_cd_a93046d6d953ea9d_e0000000::unmarshalArguments(cdrStream& _n)
{
  _n.unmarshalArrayFloat((_CORBA_Float*)((ComPcProcess::Matrix4X4F_slice*)arg_0_), 16);
  arg_0 = &arg_0_[0];

}

void _0RL_cd_a93046d6d953ea9d_e0000000::marshalReturnedValues(cdrStream& _n)
{
  result >>= _n;

}

void _0RL_cd_a93046d6d953ea9d_e0000000::unmarshalReturnedValues(cdrStream& _n)
{
  (::CORBA::Double&)result <<= _n;

}

const char* const _0RL_cd_a93046d6d953ea9d_e0000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_a93046d6d953ea9d_f0000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_a93046d6d953ea9d_e0000000* tcd = (_0RL_cd_a93046d6d953ea9d_e0000000*)cd;
  _impl_ComPcProcess* impl = (_impl_ComPcProcess*) svnt->_ptrToInterface(ComPcProcess::_PD_repoId);
  tcd->result = impl->add_PointCloud(tcd->arg_0);


}

::CORBA::Double _objref_ComPcProcess::add_PointCloud(const ::ComPcProcess::Matrix4X4F matrix_in)
{
  _0RL_cd_a93046d6d953ea9d_e0000000 _call_desc(_0RL_lcfn_a93046d6d953ea9d_f0000000, "add_PointCloud", 15);
  _call_desc.arg_0 = &matrix_in[0];

  _invoke(_call_desc);
  return _call_desc.result;


}
// Local call call-back function.
static void
_0RL_lcfn_a93046d6d953ea9d_01000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_a93046d6d953ea9d_e0000000* tcd = (_0RL_cd_a93046d6d953ea9d_e0000000*)cd;
  _impl_ComPcProcess* impl = (_impl_ComPcProcess*) svnt->_ptrToInterface(ComPcProcess::_PD_repoId);
  tcd->result = impl->get_FirstCloud(tcd->arg_0);


}

::CORBA::Double _objref_ComPcProcess::get_FirstCloud(const ::ComPcProcess::Matrix4X4F matrix_in)
{
  _0RL_cd_a93046d6d953ea9d_e0000000 _call_desc(_0RL_lcfn_a93046d6d953ea9d_01000000, "get_FirstCloud", 15);
  _call_desc.arg_0 = &matrix_in[0];

  _invoke(_call_desc);
  return _call_desc.result;


}
_pof_ComPcProcess::~_pof_ComPcProcess() {}


omniObjRef*
_pof_ComPcProcess::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::_objref_ComPcProcess(ior, id);
}


::CORBA::Boolean
_pof_ComPcProcess::is_a(const char* id) const
{
  if( omni::ptrStrMatch(id, ::ComPcProcess::_PD_repoId) )
    return 1;
  
  return 0;
}

const _pof_ComPcProcess _the_pof_ComPcProcess;

_impl_ComPcProcess::~_impl_ComPcProcess() {}


::CORBA::Boolean
_impl_ComPcProcess::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if( omni::strMatch(op, "get_pointCloud") ) {

    _0RL_cd_a93046d6d953ea9d_00000000 _call_desc(_0RL_lcfn_a93046d6d953ea9d_10000000, "get_pointCloud", 15, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "save_pointCloud") ) {

    _0RL_cd_a93046d6d953ea9d_20000000 _call_desc(_0RL_lcfn_a93046d6d953ea9d_30000000, "save_pointCloud", 16, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "plate_recog") ) {

    _0RL_cd_a93046d6d953ea9d_40000000 _call_desc(_0RL_lcfn_a93046d6d953ea9d_50000000, "plate_recog", 12, 1);
    _call_desc.arg_1 = _call_desc.arg_1_;
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "plate_modelling") ) {

    _0RL_cd_a93046d6d953ea9d_60000000 _call_desc(_0RL_lcfn_a93046d6d953ea9d_70000000, "plate_modelling", 16, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "single_plate_modelling") ) {

    _0RL_cd_a93046d6d953ea9d_80000000 _call_desc(_0RL_lcfn_a93046d6d953ea9d_90000000, "single_plate_modelling", 23, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "check_destination") ) {

    _0RL_cd_a93046d6d953ea9d_a0000000 _call_desc(_0RL_lcfn_a93046d6d953ea9d_b0000000, "check_destination", 18, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "height_determine") ) {

    _0RL_cd_a93046d6d953ea9d_c0000000 _call_desc(_0RL_lcfn_a93046d6d953ea9d_d0000000, "height_determine", 17, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "add_PointCloud") ) {

    _0RL_cd_a93046d6d953ea9d_e0000000 _call_desc(_0RL_lcfn_a93046d6d953ea9d_f0000000, "add_PointCloud", 15, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }

  if( omni::strMatch(op, "get_FirstCloud") ) {

    _0RL_cd_a93046d6d953ea9d_e0000000 _call_desc(_0RL_lcfn_a93046d6d953ea9d_01000000, "get_FirstCloud", 15, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
_impl_ComPcProcess::_ptrToInterface(const char* id)
{
  if( id == ::ComPcProcess::_PD_repoId )
    return (::_impl_ComPcProcess*) this;
  
  if( id == ::CORBA::Object::_PD_repoId )
    return (void*) 1;

  if( omni::strMatch(id, ::ComPcProcess::_PD_repoId) )
    return (::_impl_ComPcProcess*) this;
  
  if( omni::strMatch(id, ::CORBA::Object::_PD_repoId) )
    return (void*) 1;
  return 0;
}

const char*
_impl_ComPcProcess::_mostDerivedRepoId()
{
  return ::ComPcProcess::_PD_repoId;
}

POA_ComPcProcess::~POA_ComPcProcess() {}

